# -*- coding: utf-8 -*-
"""Pegando BP, DRE E DVA DA CVM

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15to2Bijxp2IBCXaqwuWgH6D3tUxZTh3g
"""

!pip install wget

import numpy as np
import pandas as pd
import wget
from zipfile import ZipFile
from google.colab.data_table import DataTable
import plotly.graph_objects as go

url_base = 'http://dados.cvm.gov.br/dados/CIA_ABERTA/DOC/DFP/DADOS/'

arquivos_zip = []
for ano in range(2010,2021):
  arquivos_zip.append(f'dfp_cia_aberta_{ano}.zip')

arquivos_zip

for arq in arquivos_zip:
  wget.download(url_base+arq)

for arq in arquivos_zip:
  ZipFile(arq, 'r').extractall('CVM')

!mkdir DADOS_DFP

nomes = ['BPA_con', 'BPA_ind','BPP_con','BPP_ind','DFC_MD_con','DFC_MD_ind','DFC_MI_con','DFC_MI_ind','DMPL_con','DMPL_ind','DRE_con','DRE_ind','DVA_con','DVA_ind']
for nome in nomes:
  arquivo = pd.DataFrame()
  for ano in range(2010,2021):
    arquivo = pd.concat([arquivo,pd.read_csv(f'/content/CVM/dfp_cia_aberta_{nome}_{ano}.csv', sep=';', decimal=',', encoding='ISO-8859-1')])
  arquivo.to_csv(f'DADOS_DFP/dfp_cia_aberta_{nome}_2010-2020.csv', index = False)

dre = pd.read_csv('/content/DADOS_DFP/dfp_cia_aberta_DRE_ind_2010-2020.csv')

dre = dre[dre['ORDEM_EXERC'] == "ÚLTIMO"]

dre.head(3)

empresas = dre[['DENOM_CIA','CD_CVM']].drop_duplicates().set_index('CD_CVM')
DataTable(empresas)

empresa = dre[dre['CD_CVM'] == 7617]

empresa.head()

DataTable(empresa[['CD_CONTA', 'DS_CONTA']].drop_duplicates().set_index('CD_CONTA'))

conta = empresa[empresa['CD_CONTA'] == '3.99.02.02']
conta.head()

conta.index = pd.to_datetime(conta['DT_REFER'])
conta.head()

"""***CALCULANDO O PL***"""

!pip install yfinance
import yfinance as yf

prices = yf.download('ITSA4.SA', start='2011-01-01')[['Adj Close','Close']]

prices.head()

indicadores = prices.join(conta['VL_CONTA'], how='outer')

indicadores.rename({'VL_CONTA':'LPA'}, axis=1, inplace = True)

indicadores.fillna(method='ffill', inplace=True)
indicadores.dropna(inplace=True)

indicadores['PL'] = indicadores['Close']/indicadores['LPA']
indicadores['PL_Ajustado'] = indicadores['Adj Close']/indicadores['LPA']
indicadores

fig = go.Figure()
fig.add_trace(go.Scatter(x=indicadores.index, y=indicadores['PL'], name = 'PL'))
fig.add_trace(go.Scatter(x=indicadores.index, y=indicadores['PL_Ajustado'], name = 'PL_Ajustado'))
fig.add_trace(go.Scatter(x=indicadores.index, y=indicadores['Close'], name = 'ITSA4'))
fig.add_trace(go.Scatter(x=indicadores.index, y=indicadores['Adj Close'], name = 'ITSA4_Ajustado'))







